#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yosuke sakamoto
# SPDX-License-Identifier: BSD-3-Clause

#課題3#

a="robot"
b="system"
 
#文字の連結
c=a+b
print( "%s+%s=%s" % ( a,b,c ) )
  
#文字列の繰り返し
f=a*10 
print(f) 
   
#フォーマット文字列で整形
d=format( '%s %s' % (a,b) )
print(d)
    
#置換
g=b.replace('te','TE')
print(g)
     
#文字列両端のスペース、タブ文字、改行を削除
h=' robot \n\n\n'
print(h)
i=h.strip()
print(i)

